#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yuto Osawa
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0

for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)

if ans % 2 == 0:
    print('偶数')
else:
    print('奇数')
