#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yuto Osawa
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
count = 0

for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)
    count += 1

print("合計:", ans)
print("入力された数値の個数:", count)
